services:
  - type: web
    name: spms
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate"
    startCommand: gunicorn spms.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: spms.settings
      - key: SECRET_KEY
        value: your-strong-secret-key
      - key: DATABASE_URL
        fromDatabase:
          name: spms-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        value: your_google_client_id
      - key: GOOGLE_CLIENT_SECRET
        value: your_google_client_secret
