services:
  - type: web
    name: spms
    env: python
    repo: https://github.com/qmuuoryan/SPMS
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn spms.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: spms-db
          property: connectionString
    autoDeploy: true

databases:
  - name: spms-db
    plan: free
    databaseName: spms
    user: spms_user
