# Generated by Django 5.2 on 2025-05-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registartion_number',
            new_name='registration_number',
        ),
    ]
