# Generated by Django 5.2 on 2025-05-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_registartion_number_student_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='User',
            new_name='user',
        ),
    ]
