# Generated by Django 5.2 on 2025-05-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_project_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='document',
            new_name='file',
        ),
    ]
