# Generated by Django 5.2 on 2025-06-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('supervisor', 'Supervisor'), ('lecturer', 'Lecturer'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
