# Generated by Django 5.2.3 on 2025-07-17 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_proposal_options_remove_proposal_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='backend.student'),
        ),
    ]
